### ISSUE TITLE
ERROR in L_SEMANTIC_UI_MODULE is not an NgModule

### ISSUE THREAD

**Issue by willy3615** [lon-yang/angular2-semantic-ui#10]
I did the following:
npm install angular2-semantic-ui --save

Then added 
`import { L_SEMANTIC_UI_MODULE } from 'angular2-semantic-ui'; `

to my app.module.ts along with 
```
  imports: [
    ...
    L_SEMANTIC_UI_MODULE,
    ...
  ],
```
I get the following error after restarting my server with ng serve:
```
$ ng serve
** NG Live Development Server is running on http://localhost:4200 **
Hash: a66652bc769dca727521
Time: 13802ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {5} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 72.2 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 573 kB {5} [initial] [rendered]
chunk    {3} scripts.bundle.js, scripts.bundle.js.map (scripts) 609 kB {5} [initial] [rendered]
chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.97 MB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in L_SEMANTIC_UI_MODULE is not an NgModule
webpack: Failed to compile.

```

**Comment by lon-yang** [comment]
Please try to use version **`2.0.1`**. But i think there has something wrong in angular cli.

**Comment by willy3615** [comment]
I updated to 2.0.1 but no luck. I'm still getting that same error. 

I am using angular cli which you mentioned might be the problem. Do you recommend just not using angular cli or is there another step I'm missing?

**Comment by lon-yang** [comment]
Which version are you using of angular-cli? I tested it with `1.0.0` and no error.
I have no idea why has this error when using angulr-cli. But I find that there are other libraries has the same error when using angular-cli.

**Comment by willy3615** [comment]
I'm using 1.0.0 as well. I just created a new project using angular-cli and added angular2-semantic-ui to it and got the same error `ERROR in L_SEMANTIC_UI_MODULE is not an NgModule`

You don't get the error using angular-cli then?

**Comment by lon-yang** [comment]
Sorry, It's a wrong version. I got the error too.  I will check it.

**Comment by lon-yang** [comment]
Can you try replace the **`index.d.ts`** in node_modules/angualr2-semantic-ui with:
```ts
import { NgModule } from "@angular/core";

export * from './components/checkbox';
export * from './components/dimmer';
export * from './components/dropdown';
export * from './components/loader';
export * from './components/modal';
export * from './components/progress';
export * from './components/rating';
export * from './components/tab';
export * from './components/accordion';
export * from './components/popup';
export * from './components/pagination';
export * from './components/tags-input';
export declare const SEMANTIC_UI_COMPONENTS: Array<any>;

@NgModule({})
export declare class L_SEMANTIC_UI_MODULE {
}
```

**Comment by willy3615** [comment]
Looks like that did the trick. I am no longer getting that error.

**Comment by lon-yang** [comment]
All right. I have publised version `2.0.2`. Thanks for your feedback.
