### ISSUE TITLE
angular2-sematic-ui controls throwing error on angularcli prod build

### ISSUE THREAD

**Issue by sudhakar-cloudiq** [lon-yang/angular2-semantic-ui#11]
trying to prod build using **ng build --prod** command and the build was success. The page was not loaded when i running the application and i got the error"No value accessor for form control with unspecified name attribute".

When i comment out the angular2-sematic-ui controls and the prod build application running and working properly. 

If i am using ngDefaultControl option in angular2-sematic-ui controls, the prod build application running and working properly but the  angular2-sematic-ui controls not displayed on UI.

Please help me asap.

**Comment by lon-yang** [comment]
Using ng serve is normally? Can you check which control caused this？

**Comment by sudhakar-cloudiq** [comment]
ng serve and ng build is working fine.  but not working using ng build --prod.

The controls are lsu-dropdown, lsu-modal, lsu-checkbox, lsu-accordian

**Comment by lon-yang** [comment]
Which form are you using? formBuilder or ng model?

**Comment by sudhakar-cloudiq** [comment]
ng model.

**Comment by lon-yang** [comment]
I'm not sure what's going on with `prod` build. Can you using formBuilder instead ngModel? I will check this issus.

**Comment by sudhakar-cloudiq** [comment]
ok thanks. I will try with formBuilder.

**Comment by lon-yang** [comment]
@sudhakar-cloudiq , I have tested it. I found that the error caused by `AOT `. So you can run `ng build -prod --aot=false`. It's will working fine. But this also an issue. I will fix it asap.
[#12 Support AOT](https://github.com/lon-yang/angular2-semantic-ui/issues/12)

**Comment by sudhakar-cloudiq** [comment]
It works. Thanks a lot @lon-yang.
