### ISSUE TITLE
Disabling the dropdown

### ISSUE THREAD

**Issue by tonyhensler** [lon-yang/angular2-semantic-ui#13]
#14 
Would you be able to add the following to the dropdown.ts so we can disable the dropdown box?

` <div class="ui fluid selection dropdown" [attr.id]="id"
           [ngClass]="{'active':active,'visible':active,'multiple':multiple,'disabled':disabled}"
           (click)="toggleSelectPanel($event)">`

and

`  @Input()
  public disabled: boolean = false;
`

This will give us the opportunity to disable the dropdown when needed using the following:-

`<lsu-dropdown [(ngModel)]="selectedColor" [data]="colors" [disabled]="true" [placeHolder]="'select color'"></lsu-dropdown>`

Thanks

**Comment by lon-yang** [comment]
I have already published `2.0.4`. Thanks for your pr!

**Comment by lon-yang** [comment]
Sorry, It's `2.0.5`
