### ISSUE TITLE
LSU Modal gets displayed behind the component

### ISSUE THREAD

**Issue by ivarkrs** [lon-yang/angular2-semantic-ui#18]
Hello,
I have got a strange issue(apologies in advance - not sure it is issue), LSU modal gets displayed behind the screen. It displays based on true or false, but component is visible behind the other page content.
Please refer the attached images. Second image is the dropdown which is part the of the LSU modal.
![1](https://user-images.githubusercontent.com/5013317/33255953-d574bf64-d375-11e7-8448-1d736bd4adca.png)
![2](https://user-images.githubusercontent.com/5013317/33255954-d76d615e-d375-11e7-84dc-a22215ae29b1.png)

**Comment by lon-yang** [comment]
Maybe is some other div's zIndex is too high. Can you try this what set the modal's zIndex to higher(like 9999999) ?

**Comment by ravikumarkrs** [comment]
Thanks for your quick reply. I did try this with option of giving z-index:99999999. But out of luck

**Comment by lon-yang** [comment]
Can you show me the dom source code in browser, like this
![1](https://user-images.githubusercontent.com/9428909/33259044-856789e0-d396-11e7-8f52-1045d0e4a656.PNG)

**Comment by ravikumarkrs** [comment]
Thanks again for your reply. Please find the attached image for your reference.
![3](https://user-images.githubusercontent.com/5013317/33266709-bf280924-d39c-11e7-86be-cecb6dfcc90a.png)

**Comment by lon-yang** [comment]
Sorry, I can't find any problems with those code

**Comment by ravikumarkrs** [comment]
Modal opens up, and clicking somewhere outside it gets closed.
Is there a way to force user to click either on save or cancel? Should get closed on clicking save or cancel buttons

**Comment by lon-yang** [comment]
Sorry, there is no setting to stop this event. But i can add some options in the future

**Comment by ivarkrs** [comment]
Thank you....

**Comment by lon-yang** [comment]
There has the setting. You can set the `closeable` to `false` on the `options` input param. 
e.g. 
![image](https://user-images.githubusercontent.com/9428909/33605045-110e78f2-d9f3-11e7-9830-dbaafad1c727.png)
