### ISSUE TITLE
ngModel doesn't works

### ISSUE THREAD

**Issue by JhookC** [lon-yang/angular2-semantic-ui#6]
Using system.js the components don't recognize the propertie [(ngModel)].

![image](https://cloud.githubusercontent.com/assets/5731700/20405329/9039d5fe-acd6-11e6-94d5-2a46be8b6aff.png)

**Comment by lon-yang** [comment]
Are you missing import `FormsModule`?

**Comment by JhookC** [comment]
Thanks man, that was the problem. Solved it. Sorry for the mistake, I just started learning angular 2.

**Comment by lon-yang** [comment]
: )
