### ISSUE TITLE
wrong start page pagination component

### ISSUE THREAD

**Issue by paraflu** [lon-yang/angular2-semantic-ui#7]
I've a list of 689 items 10 per page. The pagination show the last 10 page (60-69). Imho expected something like

1, 2,3,..,67,68,69 

or similar

**Comment by lon-yang** [comment]
![image](https://cloud.githubusercontent.com/assets/9428909/21737242/fd6f1d2a-d4b1-11e6-81c7-55c1e5162c1d.png)

Like this?
