### ISSUE TITLE
No compiled files

### ISSUE THREAD

**Issue by mani0608** [lon-yang/angular2-semantic-ui#9]
I used the following command to download the angular2-semantic-ui module
npm install angular2-semantic-ui --save

But i couldn't find any compile files being download. I got only *.ts files

**Comment by JhookC** [comment]
That's the way it comes, you just have to compile it. If you use an IDE like Webstorm you can setup to compile it after saving or setup your project to compile it.

This is an example of how to configure your tsconfig.json (I'm using SystemJs no WebPack):

`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
      "./node_modules/@types/"
    ]
  },
  "compileOnSave": true,
  "files": [
    "main.ts",
    "node_modules/angular2-semantic-ui/index.ts"
  ],
  "include": [
    "app/**/*.ts"
  ],
  "exclude": [
    "typings/browser.d.ts",
    "typings/browser",
  	"node_modules",
    "**/*-aot.ts"
  ]
}`

**Comment by lon-yang** [comment]
You can use the version `2.0.0`. I have published it to npm in today. But it will only support Angular 4.0.0 and later.

**Comment by mani0608** [comment]
Thanks for the suggestion @JhookC 
Thanks for the new version @lon-yang 
I did use the option suggested by @JhookC already and it worked for me. 
I will get the latest version and comeback in case.
